#!/bin/bash
# Iter-2 SSL pretraining ON TOP OF the v2 iter-1 recipe.
#
# Two compounding improvements vs. the original iter-2 (02_pretrain_ssl_iter2_100k_c8.sh):
#
#   (A) Targets come from the v2 iter-1 encoder
#       (targets_iter2_v2_c8/, generated by 01d_generate_iter2_targets_v2_c8.sh).
#       Better iter-1 → better cluster targets → stronger iter-2 supervision.
#
#   (B) The iter-2 SSL recipe itself uses the v2 training improvements:
#         - mask_prob 0.50 (HuBERT-equivalent), mask_length 10
#         - LayerDrop 0.05 in the encoder
#         - SpecAugment during SSL with live mask_emb fill
#         - Auxiliary k-means heads at the U-net bottleneck (layer 8)
#
# Warm-start: by default we initialize the encoder + mask_emb from the v2
# iter-1 checkpoint (HuBERT-style iterative training). The k-means prediction
# heads start fresh because the new k-means centroids are different.
# To force a strict from-scratch iter-2 model, set INIT_ENCODER_CHECKPOINT="".

#SBATCH --partition=common
#SBATCH --qos=bg-eng-01
#SBATCH --account=bg-eng-01
#SBATCH --job-name=csu_ssl_iter2_v2_100k_c8
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=40
#SBATCH --mem=256G
#SBATCH --gres=gpu:4
#SBATCH -o /valhalla/projects/bg-eng-01/LoreaEnc/logs/csu_ssl_iter2_v2_100k_c8.%j.out
#SBATCH -e /valhalla/projects/bg-eng-01/LoreaEnc/logs/csu_ssl_iter2_v2_100k_c8.%j.err

set -euo pipefail

module purge
module load anaconda3
module load nvidia/cuda/12

PROJECT_DIR="/valhalla/projects/${SLURM_JOB_ACCOUNT}/LoreaEnc"
VIRTUAL_ENV="/valhalla/projects/${SLURM_JOB_ACCOUNT}/conda_envs/torch"
DATA_ROOT="${DATA_ROOT:-dataset/datasets/librispeech/LibriSpeech}"
TARGETS_DIR="${TARGETS_DIR:-outputs/causal_specunit/targets_iter2_v2_c8}"
OUTPUT_DIR="${OUTPUT_DIR:-outputs/causal_specunit/pretrain_ssl_iter2_v2_100k_c8}"
SOURCE_SSL_CHECKPOINT="${SOURCE_SSL_CHECKPOINT:-outputs/causal_specunit/pretrain_ssl_v2_150k_c8/checkpoint_step150000/checkpoint.pt}"

# Warm-start from v2 iter-1 by default. Override with INIT_ENCODER_CHECKPOINT="" to disable.
INIT_ENCODER_CHECKPOINT="${INIT_ENCODER_CHECKPOINT-__DEFAULT__}"
if [ "${INIT_ENCODER_CHECKPOINT}" = "__DEFAULT__" ]; then
    INIT_ENCODER_CHECKPOINT="${SOURCE_SSL_CHECKPOINT}"
fi

# v2 SSL recipe knobs
MASK_PROB="${MASK_PROB:-0.50}"
MASK_LENGTH="${MASK_LENGTH:-10}"
LAYER_DROP_P="${LAYER_DROP_P:-0.05}"
AUX_LAYERS="${AUX_LAYERS:-8}"
AUX_WEIGHT="${AUX_WEIGHT:-0.5}"
CODEBOOK_MODE="${CODEBOOK_MODE:-both}"

MAX_STEPS="${MAX_STEPS:-100000}"
LR="${LR:-1e-3}"
WARMUP_EPOCHS="${WARMUP_EPOCHS:-20}"
PEAK_EPOCHS="${PEAK_EPOCHS:-20}"
NOAM_DECAY_RATE="${NOAM_DECAY_RATE:-1.0}"

# 4 GPUs × 64 batch × 1 accum = 256 effective batch (matches v2 iter-1).
NUM_PROCESSES=4
BATCH_SIZE="${BATCH_SIZE:-64}"
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-1}"
WORKERS="${WORKERS:-8}"
DATALOADER_TIMEOUT="${DATALOADER_TIMEOUT:-300}"

export VIRTUAL_ENV
export PATH="${VIRTUAL_ENV}/bin:${PATH}"

cd "${PROJECT_DIR}"
mkdir -p logs "${OUTPUT_DIR}"

[ -d "${VIRTUAL_ENV}" ] || { echo "Missing venv: ${VIRTUAL_ENV}"; exit 1; }
[ -d "${DATA_ROOT}" ]   || { echo "Missing data root: ${DATA_ROOT}"; exit 1; }
[ -f "${TARGETS_DIR}/targets.pt" ]    || { echo "Missing iter-2 targets: ${TARGETS_DIR}/targets.pt"; echo "Run 01d_generate_iter2_targets_v2_c8.sh first."; exit 1; }
[ -f "${TARGETS_DIR}/cmvn.pt" ]       || { echo "Missing iter-2 CMVN"; exit 1; }
[ -f "${TARGETS_DIR}/metadata.json" ] || { echo "Missing iter-2 metadata"; exit 1; }
if [ -n "${INIT_ENCODER_CHECKPOINT}" ] \
    && [ ! -f "${INIT_ENCODER_CHECKPOINT}" ] \
    && [ ! -f "${INIT_ENCODER_CHECKPOINT}/checkpoint.pt" ]; then
    echo "Missing init encoder checkpoint: ${INIT_ENCODER_CHECKPOINT}"; exit 1
fi

if [ ! -f "${TARGETS_DIR}/target_index.json" ]; then
    echo "Creating sharded targets..."
    python -m CausalSpecUnit.shard_targets --targets-dir "${TARGETS_DIR}" --num-shards 128
fi

export TARGETS_DIR
export MASTER_ADDR="${MASTER_ADDR:-127.0.0.1}"
export MASTER_PORT="${MASTER_PORT:-$((17000 + SLURM_JOB_ID % 20000))}"
export PYTHONFAULTHANDLER=1
export PYTHONUNBUFFERED=1
export CUDA_LAUNCH_BLOCKING=0
export TOKENIZERS_PARALLELISM=false
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
export NCCL_SOCKET_IFNAME="${NCCL_SOCKET_IFNAME:-^lo,docker}"
export NCCL_RAS_ENABLE=0
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1

echo "Job ${SLURM_JOB_ID} iter-2 v2 SSL pretraining starting at $(date)"
echo "Targets:                ${TARGETS_DIR}"
echo "Output:                 ${OUTPUT_DIR}"
echo "Init encoder ckpt:      ${INIT_ENCODER_CHECKPOINT:-<from scratch>}"
echo "GPUs / workers:         ${NUM_PROCESSES} / ${WORKERS}"
echo "Max steps:              ${MAX_STEPS}"
echo "Effective batch:        $((BATCH_SIZE * NUM_PROCESSES * GRAD_ACCUM_STEPS))"
echo "v2 recipe:              mask_prob=${MASK_PROB} layer_drop=${LAYER_DROP_P} aux_layers=${AUX_LAYERS} aux_weight=${AUX_WEIGHT} codebook_mode=${CODEBOOK_MODE} specaug=on"

python - <<'PY'
import json, os, torch
print("PyTorch:", torch.__version__)
with open(os.path.join(os.environ["TARGETS_DIR"], "metadata.json"), encoding="utf-8") as f:
    metadata = json.load(f)
print("Iter-2 (v2) target metadata:", {k: metadata.get(k) for k in
      ["target_features","chunk_size","chunk_stride","pca_dim","k_coarse","k_fine","num_target_utterances","num_encoder_frames"]})
PY

RESUME_CKPT="${RESUME_CKPT:-}"
EXTRA_ARGS=()
if [ -n "${RESUME_CKPT}" ]; then
    [ -f "${RESUME_CKPT}/checkpoint.pt" ] || { echo "RESUME_CKPT bad: ${RESUME_CKPT}"; exit 1; }
    EXTRA_ARGS+=(--resume "${RESUME_CKPT}")
elif [ -n "${INIT_ENCODER_CHECKPOINT}" ]; then
    EXTRA_ARGS+=(--init-encoder-checkpoint "${INIT_ENCODER_CHECKPOINT}")
fi

read -r -a AUX_LAYERS_ARGS <<< "${AUX_LAYERS}"

torchrun \
    --nproc_per_node="${NUM_PROCESSES}" \
    --master_addr="${MASTER_ADDR}" \
    --master_port="${MASTER_PORT}" \
    -m CausalSpecUnit.pretrain_ssl \
    --data-root "${DATA_ROOT}" \
    --targets-dir "${TARGETS_DIR}" \
    --output-dir "${OUTPUT_DIR}" \
    --variant xs \
    --epochs 1000 \
    --max-steps "${MAX_STEPS}" \
    --batch-size "${BATCH_SIZE}" \
    --grad-accum-steps "${GRAD_ACCUM_STEPS}" \
    --codebook-mode "${CODEBOOK_MODE}" \
    --mask-prob "${MASK_PROB}" \
    --mask-length "${MASK_LENGTH}" \
    --chunk-size 8 \
    --chunk-stride 4 \
    --layer-drop-p "${LAYER_DROP_P}" \
    --aux-layers "${AUX_LAYERS_ARGS[@]}" \
    --aux-weight "${AUX_WEIGHT}" \
    --specaug \
    --specaug-time-mask-param 30 \
    --specaug-freq-mask-param 20 \
    --specaug-time-masks 2 \
    --specaug-freq-masks 2 \
    --lr "${LR}" \
    --warmup-epochs "${WARMUP_EPOCHS}" \
    --peak-epochs "${PEAK_EPOCHS}" \
    --noam-decay-rate "${NOAM_DECAY_RATE}" \
    --max-grad-norm 1.0 \
    --max-safe-grad-norm 200.0 \
    --workers "${WORKERS}" \
    --dataloader-timeout "${DATALOADER_TIMEOUT}" \
    --prefetch-factor 4 \
    --log-every 100 \
    --save-every 5 \
    --trace-startup \
    --progress off \
    "${EXTRA_ARGS[@]}"

echo "Job ${SLURM_JOB_ID} iter-2 v2 SSL pretraining finished at $(date)"
echo "Final checkpoint: ${OUTPUT_DIR}/checkpoint_step$(printf '%06d' ${MAX_STEPS})/checkpoint.pt"
